version: '3'
services:
  web:
    build: .
    ports:
     - "8080:3000"
    environment:
      DB_HOST: mongodb://mongodb:27017
    depends_on:
      - "mongodb"
  mongodb:
    image: "mongo:4.1.7-xenial"